/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGAddressResource.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGAddressResource::SWGAddressResource(QString* json) {
    init();
    this->fromJson(*json);
}

SWGAddressResource::SWGAddressResource() {
    init();
}

SWGAddressResource::~SWGAddressResource() {
    this->cleanup();
}

void
SWGAddressResource::init() {
    address1 = new QString("");
    address2 = new QString("");
    city = new QString("");
    country_code = new QString("");
    postal_code = new QString("");
    state_code = new QString("");
}

void
SWGAddressResource::cleanup() {
    
    if(address1 != nullptr) {
        delete address1;
    }

    if(address2 != nullptr) {
        delete address2;
    }

    if(city != nullptr) {
        delete city;
    }

    if(country_code != nullptr) {
        delete country_code;
    }

    if(postal_code != nullptr) {
        delete postal_code;
    }

    if(state_code != nullptr) {
        delete state_code;
    }
}

SWGAddressResource*
SWGAddressResource::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGAddressResource::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&address1, pJson["address1"], "QString", "QString");
    ::Swagger::setValue(&address2, pJson["address2"], "QString", "QString");
    ::Swagger::setValue(&city, pJson["city"], "QString", "QString");
    ::Swagger::setValue(&country_code, pJson["country_code"], "QString", "QString");
    ::Swagger::setValue(&postal_code, pJson["postal_code"], "QString", "QString");
    ::Swagger::setValue(&state_code, pJson["state_code"], "QString", "QString");
}

QString
SWGAddressResource::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGAddressResource::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    toJsonValue(QString("address1"), address1, obj, QString("QString"));

    toJsonValue(QString("address2"), address2, obj, QString("QString"));

    toJsonValue(QString("city"), city, obj, QString("QString"));

    toJsonValue(QString("country_code"), country_code, obj, QString("QString"));

    toJsonValue(QString("postal_code"), postal_code, obj, QString("QString"));

    toJsonValue(QString("state_code"), state_code, obj, QString("QString"));

    return obj;
}

QString*
SWGAddressResource::getAddress1() {
    return address1;
}
void
SWGAddressResource::setAddress1(QString* address1) {
    this->address1 = address1;
}

QString*
SWGAddressResource::getAddress2() {
    return address2;
}
void
SWGAddressResource::setAddress2(QString* address2) {
    this->address2 = address2;
}

QString*
SWGAddressResource::getCity() {
    return city;
}
void
SWGAddressResource::setCity(QString* city) {
    this->city = city;
}

QString*
SWGAddressResource::getCountryCode() {
    return country_code;
}
void
SWGAddressResource::setCountryCode(QString* country_code) {
    this->country_code = country_code;
}

QString*
SWGAddressResource::getPostalCode() {
    return postal_code;
}
void
SWGAddressResource::setPostalCode(QString* postal_code) {
    this->postal_code = postal_code;
}

QString*
SWGAddressResource::getStateCode() {
    return state_code;
}
void
SWGAddressResource::setStateCode(QString* state_code) {
    this->state_code = state_code;
}



} /* namespace Swagger */

