/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGArticleResource.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGArticleResource::SWGArticleResource(QString* json) {
    init();
    this->fromJson(*json);
}

SWGArticleResource::SWGArticleResource() {
    init();
}

SWGArticleResource::~SWGArticleResource() {
    this->cleanup();
}

void
SWGArticleResource::init() {
    active = false;
    additional_properties = new QMap<QString, SWGProperty>();
    body = new QString("");
    category = new SWGNestedCategory();
    created_date = 0L;
    id = new QString("");
    tags = new QList<QString*>();
    template = new QString("");
    title = new QString("");
    updated_date = 0L;
}

void
SWGArticleResource::cleanup() {
    

    if(additional_properties != nullptr) {
        QList<SWGProperty*>* arr = additional_properties;
        foreach(SWGProperty* o, *arr) {
            delete o;
        }
        delete additional_properties;
    }

    if(body != nullptr) {
        delete body;
    }

    if(category != nullptr) {
        delete category;
    }


    if(id != nullptr) {
        delete id;
    }

    if(tags != nullptr) {
        QList<QString*>* arr = tags;
        foreach(QString* o, *arr) {
            delete o;
        }
        delete tags;
    }

    if(template != nullptr) {
        delete template;
    }

    if(title != nullptr) {
        delete title;
    }

}

SWGArticleResource*
SWGArticleResource::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGArticleResource::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&active, pJson["active"], "bool", "");
    
    ::Swagger::setValue(&additional_properties, pJson["additional_properties"], "QMap", "SWGProperty");
    
    ::Swagger::setValue(&body, pJson["body"], "QString", "QString");
    ::Swagger::setValue(&category, pJson["category"], "SWGNestedCategory", "SWGNestedCategory");
    ::Swagger::setValue(&created_date, pJson["created_date"], "qint64", "");
    ::Swagger::setValue(&id, pJson["id"], "QString", "QString");
    
    ::Swagger::setValue(&tags, pJson["tags"], "QList", "QString");
    
    ::Swagger::setValue(&template, pJson["template"], "QString", "QString");
    ::Swagger::setValue(&title, pJson["title"], "QString", "QString");
    ::Swagger::setValue(&updated_date, pJson["updated_date"], "qint64", "");
}

QString
SWGArticleResource::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGArticleResource::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    obj->insert("active", QJsonValue(active));

    QJsonArray additional_propertiesJsonArray;
    toJsonArray((QList<void*>*)additional_properties, &additional_propertiesJsonArray, "additional_properties", "SWGProperty");
    obj->insert("additional_properties", additional_propertiesJsonArray);

    toJsonValue(QString("body"), body, obj, QString("QString"));

    toJsonValue(QString("category"), category, obj, QString("SWGNestedCategory"));

    obj->insert("created_date", QJsonValue(created_date));

    toJsonValue(QString("id"), id, obj, QString("QString"));

    QJsonArray tagsJsonArray;
    toJsonArray((QList<void*>*)tags, &tagsJsonArray, "tags", "QString");
    obj->insert("tags", tagsJsonArray);

    toJsonValue(QString("template"), template, obj, QString("QString"));

    toJsonValue(QString("title"), title, obj, QString("QString"));

    obj->insert("updated_date", QJsonValue(updated_date));

    return obj;
}

bool
SWGArticleResource::getActive() {
    return active;
}
void
SWGArticleResource::setActive(bool active) {
    this->active = active;
}

QMap<QString, SWGProperty*>*
SWGArticleResource::getAdditionalProperties() {
    return additional_properties;
}
void
SWGArticleResource::setAdditionalProperties(QMap<QString, SWGProperty*>* additional_properties) {
    this->additional_properties = additional_properties;
}

QString*
SWGArticleResource::getBody() {
    return body;
}
void
SWGArticleResource::setBody(QString* body) {
    this->body = body;
}

SWGNestedCategory*
SWGArticleResource::getCategory() {
    return category;
}
void
SWGArticleResource::setCategory(SWGNestedCategory* category) {
    this->category = category;
}

qint64
SWGArticleResource::getCreatedDate() {
    return created_date;
}
void
SWGArticleResource::setCreatedDate(qint64 created_date) {
    this->created_date = created_date;
}

QString*
SWGArticleResource::getId() {
    return id;
}
void
SWGArticleResource::setId(QString* id) {
    this->id = id;
}

QList<QString*>*
SWGArticleResource::getTags() {
    return tags;
}
void
SWGArticleResource::setTags(QList<QString*>* tags) {
    this->tags = tags;
}

QString*
SWGArticleResource::getTemplate() {
    return template;
}
void
SWGArticleResource::setTemplate(QString* template) {
    this->template = template;
}

QString*
SWGArticleResource::getTitle() {
    return title;
}
void
SWGArticleResource::setTitle(QString* title) {
    this->title = title;
}

qint64
SWGArticleResource::getUpdatedDate() {
    return updated_date;
}
void
SWGArticleResource::setUpdatedDate(qint64 updated_date) {
    this->updated_date = updated_date;
}



} /* namespace Swagger */

