/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGArtistResource.h
 * 
 * 
 */

#ifndef SWGArtistResource_H_
#define SWGArtistResource_H_

#include <QJsonObject>


#include "SWGContributionResource.h"
#include "SWGProperty.h"
#include <QList>
#include <QMap>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGArtistResource: public SWGObject {
public:
    SWGArtistResource();
    SWGArtistResource(QString* json);
    virtual ~SWGArtistResource();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGArtistResource* fromJson(QString &jsonString);

    QMap<QString, SWGProperty*>* getAdditionalProperties();
    void setAdditionalProperties(QMap<QString, SWGProperty*>* additional_properties);

    QString* getBorn();
    void setBorn(QString* born);

    qint32 getContributionCount();
    void setContributionCount(qint32 contribution_count);

    QList<SWGContributionResource*>* getContributions();
    void setContributions(QList<SWGContributionResource*>* contributions);

    qint64 getCreatedDate();
    void setCreatedDate(qint64 created_date);

    QString* getDied();
    void setDied(QString* died);

    qint64 getId();
    void setId(qint64 id);

    QString* getLongDescription();
    void setLongDescription(QString* long_description);

    QString* getName();
    void setName(QString* name);

    qint32 getPriority();
    void setPriority(qint32 priority);

    QString* getShortDescription();
    void setShortDescription(QString* short_description);

    QString* getTemplate();
    void setTemplate(QString* template);

    qint64 getUpdatedDate();
    void setUpdatedDate(qint64 updated_date);


private:
    QMap<QString, SWGProperty*>* additional_properties;
    QString* born;
    qint32 contribution_count;
    QList<SWGContributionResource*>* contributions;
    qint64 created_date;
    QString* died;
    qint64 id;
    QString* long_description;
    QString* name;
    qint32 priority;
    QString* short_description;
    QString* template;
    qint64 updated_date;
};

} /* namespace Swagger */

#endif /* SWGArtistResource_H_ */
