/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#include "SWGBRERuleEngineEventsApi.h"
#include "SWGHelpers.h"
#include "SWGModelFactory.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace Swagger {
SWGBRERuleEngineEventsApi::SWGBRERuleEngineEventsApi() {}

SWGBRERuleEngineEventsApi::~SWGBRERuleEngineEventsApi() {}

SWGBRERuleEngineEventsApi::SWGBRERuleEngineEventsApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
SWGBRERuleEngineEventsApi::sendBREEvent(SWGBreEvent bre_event) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/bre/events");



    HttpRequestWorker *worker = new HttpRequestWorker();
    HttpRequestInput input(fullPath, "POST");

    
    QString output = bre_event.asJson();
    input.request_body.append(output);
    


    connect(worker,
            &HttpRequestWorker::on_execution_finished,
            this,
            &SWGBRERuleEngineEventsApi::sendBREEventCallback);

    worker->execute(&input);
}

void
SWGBRERuleEngineEventsApi::sendBREEventCallback(HttpRequestWorker * worker) {
    QString msg;
    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }

    

    worker->deleteLater();

    
    emit sendBREEventSignal();
}
} /* namespace Swagger */
