/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGBehavior.h
 * 
 * 
 */

#ifndef SWGBehavior_H_
#define SWGBehavior_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGBehavior: public SWGObject {
public:
    SWGBehavior();
    SWGBehavior(QString* json);
    virtual ~SWGBehavior();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGBehavior* fromJson(QString &jsonString);

    QString* getDescription();
    void setDescription(QString* description);

    QString* getTypeHint();
    void setTypeHint(QString* type_hint);


private:
    QString* description;
    QString* type_hint;
};

} /* namespace Swagger */

#endif /* SWGBehavior_H_ */
