/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGBreTriggerParameterDefinition.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGBreTriggerParameterDefinition::SWGBreTriggerParameterDefinition(QString* json) {
    init();
    this->fromJson(*json);
}

SWGBreTriggerParameterDefinition::SWGBreTriggerParameterDefinition() {
    init();
}

SWGBreTriggerParameterDefinition::~SWGBreTriggerParameterDefinition() {
    this->cleanup();
}

void
SWGBreTriggerParameterDefinition::init() {
    name = new QString("");
    type = new QString("");
}

void
SWGBreTriggerParameterDefinition::cleanup() {
    
    if(name != nullptr) {
        delete name;
    }

    if(type != nullptr) {
        delete type;
    }
}

SWGBreTriggerParameterDefinition*
SWGBreTriggerParameterDefinition::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGBreTriggerParameterDefinition::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&name, pJson["name"], "QString", "QString");
    ::Swagger::setValue(&type, pJson["type"], "QString", "QString");
}

QString
SWGBreTriggerParameterDefinition::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGBreTriggerParameterDefinition::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    toJsonValue(QString("name"), name, obj, QString("QString"));

    toJsonValue(QString("type"), type, obj, QString("QString"));

    return obj;
}

QString*
SWGBreTriggerParameterDefinition::getName() {
    return name;
}
void
SWGBreTriggerParameterDefinition::setName(QString* name) {
    this->name = name;
}

QString*
SWGBreTriggerParameterDefinition::getType() {
    return type;
}
void
SWGBreTriggerParameterDefinition::setType(QString* type) {
    this->type = type;
}



} /* namespace Swagger */

