/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGBreCategoryResource.h
 * 
 * 
 */

#ifndef SWGBreCategoryResource_H_
#define SWGBreCategoryResource_H_

#include <QJsonObject>


#include "SWGProperty.h"
#include <QList>
#include <QMap>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGBreCategoryResource: public SWGObject {
public:
    SWGBreCategoryResource();
    SWGBreCategoryResource(QString* json);
    virtual ~SWGBreCategoryResource();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGBreCategoryResource* fromJson(QString &jsonString);

    QMap<QString, SWGProperty*>* getAdditionalProperties();
    void setAdditionalProperties(QMap<QString, SWGProperty*>* additional_properties);

    QString* getName();
    void setName(QString* name);

    QString* getTemplate();
    void setTemplate(QString* template);


private:
    QMap<QString, SWGProperty*>* additional_properties;
    QString* name;
    QString* template;
};

} /* namespace Swagger */

#endif /* SWGBreCategoryResource_H_ */
