/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGCouponDefinition.h
 * 
 * 
 */

#ifndef SWGCouponDefinition_H_
#define SWGCouponDefinition_H_

#include <QJsonObject>


#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGCouponDefinition: public SWGObject {
public:
    SWGCouponDefinition();
    SWGCouponDefinition(QString* json);
    virtual ~SWGCouponDefinition();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGCouponDefinition* fromJson(QString &jsonString);

    QString* getCode();
    void setCode(QString* code);

    QString* getDescription();
    void setDescription(QString* description);

    QString* getDiscountType();
    void setDiscountType(QString* discount_type);

    bool getExclusive();
    void setExclusive(bool exclusive);

    double getMaxDiscount();
    void setMaxDiscount(double max_discount);

    qint32 getMaxQuantity();
    void setMaxQuantity(qint32 max_quantity);

    double getMinCartTotal();
    void setMinCartTotal(double min_cart_total);

    QString* getName();
    void setName(QString* name);

    bool getSelfExclusive();
    void setSelfExclusive(bool self_exclusive);

    qint32 getTargetItemId();
    void setTargetItemId(qint32 target_item_id);

    QString* getType();
    void setType(QString* type);

    QList<QString*>* getValidForTags();
    void setValidForTags(QList<QString*>* valid_for_tags);

    double getValue();
    void setValue(double value);

    qint32 getVendorId();
    void setVendorId(qint32 vendor_id);


private:
    QString* code;
    QString* description;
    QString* discount_type;
    bool exclusive;
    double max_discount;
    qint32 max_quantity;
    double min_cart_total;
    QString* name;
    bool self_exclusive;
    qint32 target_item_id;
    QString* type;
    QList<QString*>* valid_for_tags;
    double value;
    qint32 vendor_id;
};

} /* namespace Swagger */

#endif /* SWGCouponDefinition_H_ */
