/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGContributionResource.h
 * 
 * 
 */

#ifndef SWGContributionResource_H_
#define SWGContributionResource_H_

#include <QJsonObject>


#include "SWGSimpleReferenceResource«long».h"
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGContributionResource: public SWGObject {
public:
    SWGContributionResource();
    SWGContributionResource(QString* json);
    virtual ~SWGContributionResource();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGContributionResource* fromJson(QString &jsonString);

    SWGSimpleReferenceResource«long»* getArtist();
    void setArtist(SWGSimpleReferenceResource«long»* artist);

    SWGSimpleReferenceResource«long»* getMedia();
    void setMedia(SWGSimpleReferenceResource«long»* media);

    QString* getRole();
    void setRole(QString* role);


private:
    SWGSimpleReferenceResource«long»* artist;
    SWGSimpleReferenceResource«long»* media;
    QString* role;
};

} /* namespace Swagger */

#endif /* SWGContributionResource_H_ */
