/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGCartSummary.h
 * 
 * 
 */

#ifndef SWGCartSummary_H_
#define SWGCartSummary_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGCartSummary: public SWGObject {
public:
    SWGCartSummary();
    SWGCartSummary(QString* json);
    virtual ~SWGCartSummary();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGCartSummary* fromJson(QString &jsonString);

    qint64 getCreatedDate();
    void setCreatedDate(qint64 created_date);

    QString* getCurrencyCode();
    void setCurrencyCode(QString* currency_code);

    double getGrandTotal();
    void setGrandTotal(double grand_total);

    QString* getId();
    void setId(QString* id);

    double getInvoiceId();
    void setInvoiceId(double invoice_id);

    qint32 getItemsInCart();
    void setItemsInCart(qint32 items_in_cart);

    QString* getStatus();
    void setStatus(QString* status);

    double getSubtotal();
    void setSubtotal(double subtotal);


private:
    qint64 created_date;
    QString* currency_code;
    double grand_total;
    QString* id;
    double invoice_id;
    qint32 items_in_cart;
    QString* status;
    double subtotal;
};

} /* namespace Swagger */

#endif /* SWGCartSummary_H_ */
