/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGDiscount.h
 * 
 * 
 */

#ifndef SWGDiscount_H_
#define SWGDiscount_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGDiscount: public SWGObject {
public:
    SWGDiscount();
    SWGDiscount(QString* json);
    virtual ~SWGDiscount();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGDiscount* fromJson(QString &jsonString);

    QString* getDescription();
    void setDescription(QString* description);

    QString* getName();
    void setName(QString* name);

    QString* getSku();
    void setSku(QString* sku);

    double getValue();
    void setValue(double value);


private:
    QString* description;
    QString* name;
    QString* sku;
    double value;
};

} /* namespace Swagger */

#endif /* SWGDiscount_H_ */
