/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGDispositionCount.h
 * 
 * 
 */

#ifndef SWGDispositionCount_H_
#define SWGDispositionCount_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGDispositionCount: public SWGObject {
public:
    SWGDispositionCount();
    SWGDispositionCount(QString* json);
    virtual ~SWGDispositionCount();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGDispositionCount* fromJson(QString &jsonString);

    qint64 getCount();
    void setCount(qint64 count);

    QString* getName();
    void setName(QString* name);


private:
    qint64 count;
    QString* name;
};

} /* namespace Swagger */

#endif /* SWGDispositionCount_H_ */
