/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGFulfillmentType.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGFulfillmentType::SWGFulfillmentType(QString* json) {
    init();
    this->fromJson(*json);
}

SWGFulfillmentType::SWGFulfillmentType() {
    init();
}

SWGFulfillmentType::~SWGFulfillmentType() {
    this->cleanup();
}

void
SWGFulfillmentType::init() {
    core = false;
    description = new QString("");
    id = 0;
    name = new QString("");
}

void
SWGFulfillmentType::cleanup() {
    

    if(description != nullptr) {
        delete description;
    }


    if(name != nullptr) {
        delete name;
    }
}

SWGFulfillmentType*
SWGFulfillmentType::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGFulfillmentType::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&core, pJson["core"], "bool", "");
    ::Swagger::setValue(&description, pJson["description"], "QString", "QString");
    ::Swagger::setValue(&id, pJson["id"], "qint32", "");
    ::Swagger::setValue(&name, pJson["name"], "QString", "QString");
}

QString
SWGFulfillmentType::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGFulfillmentType::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    obj->insert("core", QJsonValue(core));

    toJsonValue(QString("description"), description, obj, QString("QString"));

    obj->insert("id", QJsonValue(id));

    toJsonValue(QString("name"), name, obj, QString("QString"));

    return obj;
}

bool
SWGFulfillmentType::getCore() {
    return core;
}
void
SWGFulfillmentType::setCore(bool core) {
    this->core = core;
}

QString*
SWGFulfillmentType::getDescription() {
    return description;
}
void
SWGFulfillmentType::setDescription(QString* description) {
    this->description = description;
}

qint32
SWGFulfillmentType::getId() {
    return id;
}
void
SWGFulfillmentType::setId(qint32 id) {
    this->id = id;
}

QString*
SWGFulfillmentType::getName() {
    return name;
}
void
SWGFulfillmentType::setName(QString* name) {
    this->name = name;
}



} /* namespace Swagger */

