/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGFulfillmentType.h
 * 
 * 
 */

#ifndef SWGFulfillmentType_H_
#define SWGFulfillmentType_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGFulfillmentType: public SWGObject {
public:
    SWGFulfillmentType();
    SWGFulfillmentType(QString* json);
    virtual ~SWGFulfillmentType();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGFulfillmentType* fromJson(QString &jsonString);

    bool getCore();
    void setCore(bool core);

    QString* getDescription();
    void setDescription(QString* description);

    qint32 getId();
    void setId(qint32 id);

    QString* getName();
    void setName(QString* name);


private:
    bool core;
    QString* description;
    qint32 id;
    QString* name;
};

} /* namespace Swagger */

#endif /* SWGFulfillmentType_H_ */
