/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGGroupMemberResource.h
 * 
 * 
 */

#ifndef SWGGroupMemberResource_H_
#define SWGGroupMemberResource_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGGroupMemberResource: public SWGObject {
public:
    SWGGroupMemberResource();
    SWGGroupMemberResource(QString* json);
    virtual ~SWGGroupMemberResource();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGGroupMemberResource* fromJson(QString &jsonString);

    QString* getAvatarUrl();
    void setAvatarUrl(QString* avatar_url);

    QString* getDisplayName();
    void setDisplayName(QString* display_name);

    qint32 getId();
    void setId(qint32 id);

    QString* getStatus();
    void setStatus(QString* status);

    QString* getUsername();
    void setUsername(QString* username);


private:
    QString* avatar_url;
    QString* display_name;
    qint32 id;
    QString* status;
    QString* username;
};

} /* namespace Swagger */

#endif /* SWGGroupMemberResource_H_ */
