/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGInvoiceLogEntry.h
 * 
 * 
 */

#ifndef SWGInvoiceLogEntry_H_
#define SWGInvoiceLogEntry_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGInvoiceLogEntry: public SWGObject {
public:
    SWGInvoiceLogEntry();
    SWGInvoiceLogEntry(QString* json);
    virtual ~SWGInvoiceLogEntry();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGInvoiceLogEntry* fromJson(QString &jsonString);

    qint64 getDate();
    void setDate(qint64 date);

    qint32 getInvoiceId();
    void setInvoiceId(qint32 invoice_id);

    QString* getMessage();
    void setMessage(QString* message);

    QString* getType();
    void setType(QString* type);


private:
    qint64 date;
    qint32 invoice_id;
    QString* message;
    QString* type;
};

} /* namespace Swagger */

#endif /* SWGInvoiceLogEntry_H_ */
