/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGItemBehaviorDefinitionResource.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGItemBehaviorDefinitionResource::SWGItemBehaviorDefinitionResource(QString* json) {
    init();
    this->fromJson(*json);
}

SWGItemBehaviorDefinitionResource::SWGItemBehaviorDefinitionResource() {
    init();
}

SWGItemBehaviorDefinitionResource::~SWGItemBehaviorDefinitionResource() {
    this->cleanup();
}

void
SWGItemBehaviorDefinitionResource::init() {
    behavior = new SWGBehavior();
    modifiable = false;
    required = false;
}

void
SWGItemBehaviorDefinitionResource::cleanup() {
    
    if(behavior != nullptr) {
        delete behavior;
    }


}

SWGItemBehaviorDefinitionResource*
SWGItemBehaviorDefinitionResource::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGItemBehaviorDefinitionResource::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&behavior, pJson["behavior"], "SWGBehavior", "SWGBehavior");
    ::Swagger::setValue(&modifiable, pJson["modifiable"], "bool", "");
    ::Swagger::setValue(&required, pJson["required"], "bool", "");
}

QString
SWGItemBehaviorDefinitionResource::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGItemBehaviorDefinitionResource::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    toJsonValue(QString("behavior"), behavior, obj, QString("SWGBehavior"));

    obj->insert("modifiable", QJsonValue(modifiable));

    obj->insert("required", QJsonValue(required));

    return obj;
}

SWGBehavior*
SWGItemBehaviorDefinitionResource::getBehavior() {
    return behavior;
}
void
SWGItemBehaviorDefinitionResource::setBehavior(SWGBehavior* behavior) {
    this->behavior = behavior;
}

bool
SWGItemBehaviorDefinitionResource::getModifiable() {
    return modifiable;
}
void
SWGItemBehaviorDefinitionResource::setModifiable(bool modifiable) {
    this->modifiable = modifiable;
}

bool
SWGItemBehaviorDefinitionResource::getRequired() {
    return required;
}
void
SWGItemBehaviorDefinitionResource::setRequired(bool required) {
    this->required = required;
}



} /* namespace Swagger */

