/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGKeyValuePair«string,string».h
 * 
 * 
 */

#ifndef SWGKeyValuePair«string,string»_H_
#define SWGKeyValuePair«string,string»_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGKeyValuePair«string,string»: public SWGObject {
public:
    SWGKeyValuePair«string,string»();
    SWGKeyValuePair«string,string»(QString* json);
    virtual ~SWGKeyValuePair«string,string»();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGKeyValuePair«string,string»* fromJson(QString &jsonString);

    QString* getKey();
    void setKey(QString* key);

    QString* getValue();
    void setValue(QString* value);


private:
    QString* key;
    QString* value;
};

} /* namespace Swagger */

#endif /* SWGKeyValuePair«string,string»_H_ */
