/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_SWGMessagingApi_H_
#define _SWG_SWGMessagingApi_H_

#include "SWGHttpRequest.h"

#include "SWGRawEmailResource.h"
#include "SWGRawSMSResource.h"
#include "SWGResult.h"
#include "SWGTemplateEmailResource.h"
#include "SWGTemplateSMSResource.h"

#include <QObject>

namespace Swagger {

class SWGMessagingApi: public QObject {
    Q_OBJECT

public:
    SWGMessagingApi();
    SWGMessagingApi(QString host, QString basePath);
    ~SWGMessagingApi();

    QString host;
    QString basePath;

    void sendRawEmail(SWGRawEmailResource raw_email_resource);
    void sendRawSMS(SWGRawSMSResource raw_sms_resource);
    void sendTemplatedEmail(SWGTemplateEmailResource message_resource);
    void sendTemplatedSMS(SWGTemplateSMSResource template_sms_resource);
    
private:
    void sendRawEmailCallback (HttpRequestWorker * worker);
    void sendRawSMSCallback (HttpRequestWorker * worker);
    void sendTemplatedEmailCallback (HttpRequestWorker * worker);
    void sendTemplatedSMSCallback (HttpRequestWorker * worker);
    
signals:
    void sendRawEmailSignal();
    void sendRawSMSSignal();
    void sendTemplatedEmailSignal();
    void sendTemplatedSMSSignal();
    
};
}
#endif
