/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGMaintenance.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGMaintenance::SWGMaintenance(QString* json) {
    init();
    this->fromJson(*json);
}

SWGMaintenance::SWGMaintenance() {
    init();
}

SWGMaintenance::~SWGMaintenance() {
    this->cleanup();
}

void
SWGMaintenance::init() {
    access_locked = false;
    details = NULL;
    message = new QString("");
}

void
SWGMaintenance::cleanup() {
    

    if(details != nullptr) {
        delete details;
    }

    if(message != nullptr) {
        delete message;
    }
}

SWGMaintenance*
SWGMaintenance::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGMaintenance::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&access_locked, pJson["access_locked"], "bool", "");
    ::Swagger::setValue(&details, pJson["details"], "SWGObject", "SWGObject");
    ::Swagger::setValue(&message, pJson["message"], "QString", "QString");
}

QString
SWGMaintenance::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGMaintenance::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    obj->insert("access_locked", QJsonValue(access_locked));

    toJsonValue(QString("details"), details, obj, QString("SWGObject"));

    toJsonValue(QString("message"), message, obj, QString("QString"));

    return obj;
}

bool
SWGMaintenance::getAccessLocked() {
    return access_locked;
}
void
SWGMaintenance::setAccessLocked(bool access_locked) {
    this->access_locked = access_locked;
}

SWGObject*
SWGMaintenance::getDetails() {
    return details;
}
void
SWGMaintenance::setDetails(SWGObject* details) {
    this->details = details;
}

QString*
SWGMaintenance::getMessage() {
    return message;
}
void
SWGMaintenance::setMessage(QString* message) {
    this->message = message;
}



} /* namespace Swagger */

