/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGOauthAccessTokenResource.h
 * 
 * 
 */

#ifndef SWGOauthAccessTokenResource_H_
#define SWGOauthAccessTokenResource_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGOauthAccessTokenResource: public SWGObject {
public:
    SWGOauthAccessTokenResource();
    SWGOauthAccessTokenResource(QString* json);
    virtual ~SWGOauthAccessTokenResource();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGOauthAccessTokenResource* fromJson(QString &jsonString);

    QString* getClientId();
    void setClientId(QString* client_id);

    QString* getToken();
    void setToken(QString* token);

    QString* getUsername();
    void setUsername(QString* username);


private:
    QString* client_id;
    QString* token;
    QString* username;
};

} /* namespace Swagger */

#endif /* SWGOauthAccessTokenResource_H_ */
