/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGProperty.h
 * 
 * 
 */

#ifndef SWGProperty_H_
#define SWGProperty_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGProperty: public SWGObject {
public:
    SWGProperty();
    SWGProperty(QString* json);
    virtual ~SWGProperty();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGProperty* fromJson(QString &jsonString);

    QString* getType();
    void setType(QString* type);


private:
    QString* type;
};

} /* namespace Swagger */

#endif /* SWGProperty_H_ */
