/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGRole.h
 * 
 * 
 */

#ifndef SWGRole_H_
#define SWGRole_H_

#include <QJsonObject>


#include "SWGPermission.h"
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGRole: public SWGObject {
public:
    SWGRole();
    SWGRole(QString* json);
    virtual ~SWGRole();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGRole* fromJson(QString &jsonString);

    qint32 getClientCount();
    void setClientCount(qint32 client_count);

    qint64 getCreatedDate();
    void setCreatedDate(qint64 created_date);

    qint32 getId();
    void setId(qint32 id);

    bool getLocked();
    void setLocked(bool locked);

    QString* getName();
    void setName(QString* name);

    QString* getRole();
    void setRole(QString* role);

    QList<SWGPermission*>* getRolePermission();
    void setRolePermission(QList<SWGPermission*>* role_permission);

    qint32 getUserCount();
    void setUserCount(qint32 user_count);


private:
    qint32 client_count;
    qint64 created_date;
    qint32 id;
    bool locked;
    QString* name;
    QString* role;
    QList<SWGPermission*>* role_permission;
    qint32 user_count;
};

} /* namespace Swagger */

#endif /* SWGRole_H_ */
