/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGRefundResource.h
 * 
 * 
 */

#ifndef SWGRefundResource_H_
#define SWGRefundResource_H_

#include <QJsonObject>



#include "SWGObject.h"


namespace Swagger {

class SWGRefundResource: public SWGObject {
public:
    SWGRefundResource();
    SWGRefundResource(QString* json);
    virtual ~SWGRefundResource();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGRefundResource* fromJson(QString &jsonString);

    double getAmount();
    void setAmount(double amount);

    qint32 getRefundTransactionId();
    void setRefundTransactionId(qint32 refund_transaction_id);

    qint32 getTransactionId();
    void setTransactionId(qint32 transaction_id);


private:
    double amount;
    qint32 refund_transaction_id;
    qint32 transaction_id;
};

} /* namespace Swagger */

#endif /* SWGRefundResource_H_ */
