/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGSchedule.h
 * 
 * 
 */

#ifndef SWGSchedule_H_
#define SWGSchedule_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGSchedule: public SWGObject {
public:
    SWGSchedule();
    SWGSchedule(QString* json);
    virtual ~SWGSchedule();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGSchedule* fromJson(QString &jsonString);

    qint32 getDuration();
    void setDuration(qint32 duration);

    QString* getDurationUnit();
    void setDurationUnit(QString* duration_unit);

    QString* getRepeat();
    void setRepeat(QString* repeat);


private:
    qint32 duration;
    QString* duration_unit;
    QString* repeat;
};

} /* namespace Swagger */

#endif /* SWGSchedule_H_ */
