/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGStripePaymentRequest.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGStripePaymentRequest::SWGStripePaymentRequest(QString* json) {
    init();
    this->fromJson(*json);
}

SWGStripePaymentRequest::SWGStripePaymentRequest() {
    init();
}

SWGStripePaymentRequest::~SWGStripePaymentRequest() {
    this->cleanup();
}

void
SWGStripePaymentRequest::init() {
    invoice_id = 0;
    token = new QString("");
}

void
SWGStripePaymentRequest::cleanup() {
    

    if(token != nullptr) {
        delete token;
    }
}

SWGStripePaymentRequest*
SWGStripePaymentRequest::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGStripePaymentRequest::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&invoice_id, pJson["invoice_id"], "qint32", "");
    ::Swagger::setValue(&token, pJson["token"], "QString", "QString");
}

QString
SWGStripePaymentRequest::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGStripePaymentRequest::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    obj->insert("invoice_id", QJsonValue(invoice_id));

    toJsonValue(QString("token"), token, obj, QString("QString"));

    return obj;
}

qint32
SWGStripePaymentRequest::getInvoiceId() {
    return invoice_id;
}
void
SWGStripePaymentRequest::setInvoiceId(qint32 invoice_id) {
    this->invoice_id = invoice_id;
}

QString*
SWGStripePaymentRequest::getToken() {
    return token;
}
void
SWGStripePaymentRequest::setToken(QString* token) {
    this->token = token;
}



} /* namespace Swagger */

