/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGStripeCreatePaymentMethod.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGStripeCreatePaymentMethod::SWGStripeCreatePaymentMethod(QString* json) {
    init();
    this->fromJson(*json);
}

SWGStripeCreatePaymentMethod::SWGStripeCreatePaymentMethod() {
    init();
}

SWGStripeCreatePaymentMethod::~SWGStripeCreatePaymentMethod() {
    this->cleanup();
}

void
SWGStripeCreatePaymentMethod::init() {
    token = new QString("");
    user_id = 0;
}

void
SWGStripeCreatePaymentMethod::cleanup() {
    
    if(token != nullptr) {
        delete token;
    }

}

SWGStripeCreatePaymentMethod*
SWGStripeCreatePaymentMethod::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGStripeCreatePaymentMethod::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&token, pJson["token"], "QString", "QString");
    ::Swagger::setValue(&user_id, pJson["user_id"], "qint32", "");
}

QString
SWGStripeCreatePaymentMethod::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGStripeCreatePaymentMethod::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    toJsonValue(QString("token"), token, obj, QString("QString"));

    obj->insert("user_id", QJsonValue(user_id));

    return obj;
}

QString*
SWGStripeCreatePaymentMethod::getToken() {
    return token;
}
void
SWGStripeCreatePaymentMethod::setToken(QString* token) {
    this->token = token;
}

qint32
SWGStripeCreatePaymentMethod::getUserId() {
    return user_id;
}
void
SWGStripeCreatePaymentMethod::setUserId(qint32 user_id) {
    this->user_id = user_id;
}



} /* namespace Swagger */

