/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGStateResource.h
 * 
 * 
 */

#ifndef SWGStateResource_H_
#define SWGStateResource_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGStateResource: public SWGObject {
public:
    SWGStateResource();
    SWGStateResource(QString* json);
    virtual ~SWGStateResource();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGStateResource* fromJson(QString &jsonString);

    QString* getCode();
    void setCode(QString* code);

    QString* getCountryCodeIso3();
    void setCountryCodeIso3(QString* country_code_iso3);

    qint32 getId();
    void setId(qint32 id);

    QString* getName();
    void setName(QString* name);


private:
    QString* code;
    QString* country_code_iso3;
    qint32 id;
    QString* name;
};

} /* namespace Swagger */

#endif /* SWGStateResource_H_ */
