/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGSku.h
 * 
 * 
 */

#ifndef SWGSku_H_
#define SWGSku_H_

#include <QJsonObject>


#include "SWGProperty.h"
#include <QList>
#include <QMap>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGSku: public SWGObject {
public:
    SWGSku();
    SWGSku(QString* json);
    virtual ~SWGSku();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGSku* fromJson(QString &jsonString);

    QMap<QString, SWGProperty*>* getAdditionalProperties();
    void setAdditionalProperties(QMap<QString, SWGProperty*>* additional_properties);

    QString* getCurrencyCode();
    void setCurrencyCode(QString* currency_code);

    QString* getDescription();
    void setDescription(QString* description);

    qint32 getInventory();
    void setInventory(qint32 inventory);

    qint32 getMinInventoryThreshold();
    void setMinInventoryThreshold(qint32 min_inventory_threshold);

    double getOriginalPrice();
    void setOriginalPrice(double original_price);

    double getPrice();
    void setPrice(double price);

    bool getPublished();
    void setPublished(bool published);

    qint32 getSaleId();
    void setSaleId(qint32 sale_id);

    QString* getSaleName();
    void setSaleName(QString* sale_name);

    QString* getSku();
    void setSku(QString* sku);

    qint64 getStartDate();
    void setStartDate(qint64 start_date);

    qint64 getStopDate();
    void setStopDate(qint64 stop_date);


private:
    QMap<QString, SWGProperty*>* additional_properties;
    QString* currency_code;
    QString* description;
    qint32 inventory;
    qint32 min_inventory_threshold;
    double original_price;
    double price;
    bool published;
    qint32 sale_id;
    QString* sale_name;
    QString* sku;
    qint64 start_date;
    qint64 stop_date;
};

} /* namespace Swagger */

#endif /* SWGSku_H_ */
