/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSearchReferenceMapping.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGSearchReferenceMapping::SWGSearchReferenceMapping(QString* json) {
    init();
    this->fromJson(*json);
}

SWGSearchReferenceMapping::SWGSearchReferenceMapping() {
    init();
}

SWGSearchReferenceMapping::~SWGSearchReferenceMapping() {
    this->cleanup();
}

void
SWGSearchReferenceMapping::init() {
    id = new QString("");
    ref_id_field = new QString("");
    ref_type = new QString("");
    source_field_to_destination_field = new QMap<QString, QString>();
    type = new QString("");
}

void
SWGSearchReferenceMapping::cleanup() {
    
    if(id != nullptr) {
        delete id;
    }

    if(ref_id_field != nullptr) {
        delete ref_id_field;
    }

    if(ref_type != nullptr) {
        delete ref_type;
    }

    if(source_field_to_destination_field != nullptr) {
        QList<QString*>* arr = source_field_to_destination_field;
        foreach(QString* o, *arr) {
            delete o;
        }
        delete source_field_to_destination_field;
    }

    if(type != nullptr) {
        delete type;
    }
}

SWGSearchReferenceMapping*
SWGSearchReferenceMapping::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSearchReferenceMapping::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&id, pJson["id"], "QString", "QString");
    ::Swagger::setValue(&ref_id_field, pJson["ref_id_field"], "QString", "QString");
    ::Swagger::setValue(&ref_type, pJson["ref_type"], "QString", "QString");
    
    ::Swagger::setValue(&source_field_to_destination_field, pJson["source_field_to_destination_field"], "QMap", "QString");
    
    ::Swagger::setValue(&type, pJson["type"], "QString", "QString");
}

QString
SWGSearchReferenceMapping::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGSearchReferenceMapping::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    toJsonValue(QString("id"), id, obj, QString("QString"));

    toJsonValue(QString("ref_id_field"), ref_id_field, obj, QString("QString"));

    toJsonValue(QString("ref_type"), ref_type, obj, QString("QString"));

    QJsonArray source_field_to_destination_fieldJsonArray;
    toJsonArray((QList<void*>*)source_field_to_destination_field, &source_field_to_destination_fieldJsonArray, "source_field_to_destination_field", "QString");
    obj->insert("source_field_to_destination_field", source_field_to_destination_fieldJsonArray);

    toJsonValue(QString("type"), type, obj, QString("QString"));

    return obj;
}

QString*
SWGSearchReferenceMapping::getId() {
    return id;
}
void
SWGSearchReferenceMapping::setId(QString* id) {
    this->id = id;
}

QString*
SWGSearchReferenceMapping::getRefIdField() {
    return ref_id_field;
}
void
SWGSearchReferenceMapping::setRefIdField(QString* ref_id_field) {
    this->ref_id_field = ref_id_field;
}

QString*
SWGSearchReferenceMapping::getRefType() {
    return ref_type;
}
void
SWGSearchReferenceMapping::setRefType(QString* ref_type) {
    this->ref_type = ref_type;
}

QMap<QString, QString*>*
SWGSearchReferenceMapping::getSourceFieldToDestinationField() {
    return source_field_to_destination_field;
}
void
SWGSearchReferenceMapping::setSourceFieldToDestinationField(QMap<QString, QString*>* source_field_to_destination_field) {
    this->source_field_to_destination_field = source_field_to_destination_field;
}

QString*
SWGSearchReferenceMapping::getType() {
    return type;
}
void
SWGSearchReferenceMapping::setType(QString* type) {
    this->type = type;
}



} /* namespace Swagger */

