/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGTemplateSMSResource.h
 * 
 * 
 */

#ifndef SWGTemplateSMSResource_H_
#define SWGTemplateSMSResource_H_

#include <QJsonObject>


#include "SWGLocalizer.h"
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGTemplateSMSResource: public SWGObject {
public:
    SWGTemplateSMSResource();
    SWGTemplateSMSResource(QString* json);
    virtual ~SWGTemplateSMSResource();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGTemplateSMSResource* fromJson(QString &jsonString);

    QString* getFrom();
    void setFrom(QString* from);

    SWGLocalizer* getLocalizer();
    void setLocalizer(SWGLocalizer* localizer);

    QList<qint32>* getRecipients();
    void setRecipients(QList<qint32>* recipients);

    QString* getTemplateKey();
    void setTemplateKey(QString* template_key);

    QList<QString*>* getTemplateVars();
    void setTemplateVars(QList<QString*>* template_vars);


private:
    QString* from;
    SWGLocalizer* localizer;
    QList<qint32>* recipients;
    QString* template_key;
    QList<QString*>* template_vars;
};

} /* namespace Swagger */

#endif /* SWGTemplateSMSResource_H_ */
