/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGUsageInfo.h
 * 
 * 
 */

#ifndef SWGUsageInfo_H_
#define SWGUsageInfo_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGUsageInfo: public SWGObject {
public:
    SWGUsageInfo();
    SWGUsageInfo(QString* json);
    virtual ~SWGUsageInfo();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGUsageInfo* fromJson(QString &jsonString);

    qint64 getCount();
    void setCount(qint64 count);

    qint64 getDate();
    void setDate(qint64 date);

    QString* getMethod();
    void setMethod(QString* method);

    QString* getUrl();
    void setUrl(QString* url);


private:
    qint64 count;
    qint64 date;
    QString* method;
    QString* url;
};

} /* namespace Swagger */

#endif /* SWGUsageInfo_H_ */
