/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGUserBaseResource.h
 * 
 * 
 */

#ifndef SWGUserBaseResource_H_
#define SWGUserBaseResource_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGUserBaseResource: public SWGObject {
public:
    SWGUserBaseResource();
    SWGUserBaseResource(QString* json);
    virtual ~SWGUserBaseResource();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGUserBaseResource* fromJson(QString &jsonString);

    QString* getAvatarUrl();
    void setAvatarUrl(QString* avatar_url);

    QString* getDisplayName();
    void setDisplayName(QString* display_name);

    QString* getEmail();
    void setEmail(QString* email);

    QString* getFullname();
    void setFullname(QString* fullname);

    qint32 getId();
    void setId(qint32 id);

    QString* getUsername();
    void setUsername(QString* username);


private:
    QString* avatar_url;
    QString* display_name;
    QString* email;
    QString* fullname;
    qint32 id;
    QString* username;
};

} /* namespace Swagger */

#endif /* SWGUserBaseResource_H_ */
