/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGUserRelationshipReferenceResource.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGUserRelationshipReferenceResource::SWGUserRelationshipReferenceResource(QString* json) {
    init();
    this->fromJson(*json);
}

SWGUserRelationshipReferenceResource::SWGUserRelationshipReferenceResource() {
    init();
}

SWGUserRelationshipReferenceResource::~SWGUserRelationshipReferenceResource() {
    this->cleanup();
}

void
SWGUserRelationshipReferenceResource::init() {
    avatar_url = new QString("");
    context = new QString("");
    display_name = new QString("");
    id = 0;
    relationship_id = 0L;
    username = new QString("");
}

void
SWGUserRelationshipReferenceResource::cleanup() {
    
    if(avatar_url != nullptr) {
        delete avatar_url;
    }

    if(context != nullptr) {
        delete context;
    }

    if(display_name != nullptr) {
        delete display_name;
    }



    if(username != nullptr) {
        delete username;
    }
}

SWGUserRelationshipReferenceResource*
SWGUserRelationshipReferenceResource::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGUserRelationshipReferenceResource::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&avatar_url, pJson["avatar_url"], "QString", "QString");
    ::Swagger::setValue(&context, pJson["context"], "QString", "QString");
    ::Swagger::setValue(&display_name, pJson["display_name"], "QString", "QString");
    ::Swagger::setValue(&id, pJson["id"], "qint32", "");
    ::Swagger::setValue(&relationship_id, pJson["relationship_id"], "qint64", "");
    ::Swagger::setValue(&username, pJson["username"], "QString", "QString");
}

QString
SWGUserRelationshipReferenceResource::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGUserRelationshipReferenceResource::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    toJsonValue(QString("avatar_url"), avatar_url, obj, QString("QString"));

    toJsonValue(QString("context"), context, obj, QString("QString"));

    toJsonValue(QString("display_name"), display_name, obj, QString("QString"));

    obj->insert("id", QJsonValue(id));

    obj->insert("relationship_id", QJsonValue(relationship_id));

    toJsonValue(QString("username"), username, obj, QString("QString"));

    return obj;
}

QString*
SWGUserRelationshipReferenceResource::getAvatarUrl() {
    return avatar_url;
}
void
SWGUserRelationshipReferenceResource::setAvatarUrl(QString* avatar_url) {
    this->avatar_url = avatar_url;
}

QString*
SWGUserRelationshipReferenceResource::getContext() {
    return context;
}
void
SWGUserRelationshipReferenceResource::setContext(QString* context) {
    this->context = context;
}

QString*
SWGUserRelationshipReferenceResource::getDisplayName() {
    return display_name;
}
void
SWGUserRelationshipReferenceResource::setDisplayName(QString* display_name) {
    this->display_name = display_name;
}

qint32
SWGUserRelationshipReferenceResource::getId() {
    return id;
}
void
SWGUserRelationshipReferenceResource::setId(qint32 id) {
    this->id = id;
}

qint64
SWGUserRelationshipReferenceResource::getRelationshipId() {
    return relationship_id;
}
void
SWGUserRelationshipReferenceResource::setRelationshipId(qint64 relationship_id) {
    this->relationship_id = relationship_id;
}

QString*
SWGUserRelationshipReferenceResource::getUsername() {
    return username;
}
void
SWGUserRelationshipReferenceResource::setUsername(QString* username) {
    this->username = username;
}



} /* namespace Swagger */

