/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGUserRelationshipResource.h
 * 
 * 
 */

#ifndef SWGUserRelationshipResource_H_
#define SWGUserRelationshipResource_H_

#include <QJsonObject>


#include "SWGSimpleUserResource.h"
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGUserRelationshipResource: public SWGObject {
public:
    SWGUserRelationshipResource();
    SWGUserRelationshipResource(QString* json);
    virtual ~SWGUserRelationshipResource();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGUserRelationshipResource* fromJson(QString &jsonString);

    SWGSimpleUserResource* getChild();
    void setChild(SWGSimpleUserResource* child);

    QString* getContext();
    void setContext(QString* context);

    qint64 getId();
    void setId(qint64 id);

    SWGSimpleUserResource* getParent();
    void setParent(SWGSimpleUserResource* parent);


private:
    SWGSimpleUserResource* child;
    QString* context;
    qint64 id;
    SWGSimpleUserResource* parent;
};

} /* namespace Swagger */

#endif /* SWGUserRelationshipResource_H_ */
