/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGVideoRelationshipResource.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGVideoRelationshipResource::SWGVideoRelationshipResource(QString* json) {
    init();
    this->fromJson(*json);
}

SWGVideoRelationshipResource::SWGVideoRelationshipResource() {
    init();
}

SWGVideoRelationshipResource::~SWGVideoRelationshipResource() {
    this->cleanup();
}

void
SWGVideoRelationshipResource::init() {
    from = new SWGSimpleReferenceResource«long»();
    id = 0L;
    relationship_details = new QString("");
    to = new SWGSimpleReferenceResource«long»();
}

void
SWGVideoRelationshipResource::cleanup() {
    
    if(from != nullptr) {
        delete from;
    }


    if(relationship_details != nullptr) {
        delete relationship_details;
    }

    if(to != nullptr) {
        delete to;
    }
}

SWGVideoRelationshipResource*
SWGVideoRelationshipResource::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGVideoRelationshipResource::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&from, pJson["from"], "SWGSimpleReferenceResource«long»", "SWGSimpleReferenceResource«long»");
    ::Swagger::setValue(&id, pJson["id"], "qint64", "");
    ::Swagger::setValue(&relationship_details, pJson["relationship_details"], "QString", "QString");
    ::Swagger::setValue(&to, pJson["to"], "SWGSimpleReferenceResource«long»", "SWGSimpleReferenceResource«long»");
}

QString
SWGVideoRelationshipResource::asJson ()
{
    QJsonObject* obj = this->asJsonObject();
    
    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGVideoRelationshipResource::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    toJsonValue(QString("from"), from, obj, QString("SWGSimpleReferenceResource«long»"));

    obj->insert("id", QJsonValue(id));

    toJsonValue(QString("relationship_details"), relationship_details, obj, QString("QString"));

    toJsonValue(QString("to"), to, obj, QString("SWGSimpleReferenceResource«long»"));

    return obj;
}

SWGSimpleReferenceResource«long»*
SWGVideoRelationshipResource::getFrom() {
    return from;
}
void
SWGVideoRelationshipResource::setFrom(SWGSimpleReferenceResource«long»* from) {
    this->from = from;
}

qint64
SWGVideoRelationshipResource::getId() {
    return id;
}
void
SWGVideoRelationshipResource::setId(qint64 id) {
    this->id = id;
}

QString*
SWGVideoRelationshipResource::getRelationshipDetails() {
    return relationship_details;
}
void
SWGVideoRelationshipResource::setRelationshipDetails(QString* relationship_details) {
    this->relationship_details = relationship_details;
}

SWGSimpleReferenceResource«long»*
SWGVideoRelationshipResource::getTo() {
    return to;
}
void
SWGVideoRelationshipResource::setTo(SWGSimpleReferenceResource«long»* to) {
    this->to = to;
}



} /* namespace Swagger */

