/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGWalletAlterRequest.h
 * 
 * 
 */

#ifndef SWGWalletAlterRequest_H_
#define SWGWalletAlterRequest_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGWalletAlterRequest: public SWGObject {
public:
    SWGWalletAlterRequest();
    SWGWalletAlterRequest(QString* json);
    virtual ~SWGWalletAlterRequest();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGWalletAlterRequest* fromJson(QString &jsonString);

    double getDelta();
    void setDelta(double delta);

    qint32 getInvoiceId();
    void setInvoiceId(qint32 invoice_id);

    QString* getReason();
    void setReason(QString* reason);

    QString* getType();
    void setType(QString* type);


private:
    double delta;
    qint32 invoice_id;
    QString* reason;
    QString* type;
};

} /* namespace Swagger */

#endif /* SWGWalletAlterRequest_H_ */
