/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGXsollaPaymentRequest.h
 * 
 * 
 */

#ifndef SWGXsollaPaymentRequest_H_
#define SWGXsollaPaymentRequest_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGXsollaPaymentRequest: public SWGObject {
public:
    SWGXsollaPaymentRequest();
    SWGXsollaPaymentRequest(QString* json);
    virtual ~SWGXsollaPaymentRequest();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGXsollaPaymentRequest* fromJson(QString &jsonString);

    qint32 getInvoiceId();
    void setInvoiceId(qint32 invoice_id);

    QString* getReturnUrl();
    void setReturnUrl(QString* return_url);


private:
    qint32 invoice_id;
    QString* return_url;
};

} /* namespace Swagger */

#endif /* SWGXsollaPaymentRequest_H_ */
